# Generated by Django 2.2.4 on 2019-11-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulllist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulllistcomic',
            name='comic',
        ),
        migrations.RemoveField(
            model_name='pulllistcomic',
            name='pull_list',
        ),
        migrations.RemoveField(
            model_name='pulllistseries',
            name='pull_list',
        ),
        migrations.RemoveField(
            model_name='pulllistseries',
            name='series',
        ),
        migrations.DeleteModel(
            name='PullList',
        ),
        migrations.DeleteModel(
            name='PullListComic',
        ),
        migrations.DeleteModel(
            name='PullListSeries',
        ),
    ]
