# Generated by Django 2.2.4 on 2019-11-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_comic_is_standard_issue'),
        ('pulllist', '0003_auto_20191109_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulllist',
            name='comics',
            field=models.ManyToManyField(blank=True, through='pulllist.PullListComic', to='comic.Comic'),
        ),
    ]
