# Generated by Django 2.2.4 on 2019-11-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulllist', '0004_pulllist_comics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulllist',
            name='comics',
            field=models.ManyToManyField(blank=True, related_name='comics_in_pull_list', through='pulllist.PullListComic', to='comic.Comic'),
        ),
    ]
