# Generated by Django 2.2.4 on 2019-11-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_comic_is_standard_issue'),
        ('pulllist', '0006_auto_20191109_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulllist',
            name='comics',
            field=models.ManyToManyField(blank=True, to='comic.Comic'),
        ),
    ]
