# Generated by Django 2.2.4 on 2019-11-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedcomic',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
