# Generated by Django 2.2.4 on 2019-11-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20191101_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedcomic',
            name='certification',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='collectedcomic',
            name='is_slabbed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='collectedcomic',
            name='bought_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collectedcomic',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collectedcomic',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='collectedcomic',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
