# Generated by Django 2.2.4 on 2019-11-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20191102_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedcomic',
            name='certification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
