# Generated by Django 2.2.4 on 2019-11-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20191102_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedcomic',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
