# Generated by Django 2.2.4 on 2019-11-02 22:25

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20191102_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedcomic',
            name='certification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collectedcomic',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[collection.models.CollectedComic.validate_grade]),
        ),
    ]
