# Generated by Django 2.2.4 on 2019-11-07 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20191102_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedcomic',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comics', to='comic.Comic'),
        ),
    ]
