# Generated by Django 2.2.4 on 2019-10-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comiccreator',
            name='comic',
        ),
    ]
