# Generated by Django 2.2.4 on 2019-10-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_comic'),
        ('creator', '0002_remove_comiccreator_comic'),
    ]

    operations = [
        migrations.AddField(
            model_name='comiccreator',
            name='comic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comic.Comic'),
            preserve_default=False,
        ),
    ]
