# Generated by Django 2.2.4 on 2019-10-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publisher', '0001_initial'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_id', models.CharField(blank=True, max_length=100, null=True)),
                ('diamond_id', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('item_number', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('release_date', models.DateTimeField(null=True)),
                ('cover_price', models.CharField(blank=True, max_length=100)),
                ('cover_url', models.URLField(default='www.tempurl.com')),
                ('description', models.TextField(blank=True)),
                ('page_count', models.PositiveSmallIntegerField(null=True)),
                ('barcode', models.CharField(blank=True, max_length=200)),
                ('printing', models.PositiveSmallIntegerField(default=1)),
                ('format_type', models.CharField(blank=True, max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('solicit_date', models.DateTimeField(null=True)),
                ('is_mature', models.BooleanField(default=False)),
                ('versions', models.PositiveSmallIntegerField(default=0)),
                ('variant_code', models.CharField(blank=True, max_length=100, null=True)),
                ('total_wanted', models.PositiveIntegerField(default=0)),
                ('total_favorited', models.PositiveIntegerField(default=0)),
                ('total_owned', models.PositiveIntegerField(default=0)),
                ('total_read', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('imprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Imprint')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series')),
                ('version_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comic.Comic')),
            ],
        ),
    ]
