# Generated by Django 2.2.4 on 2019-10-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_remove_comiccharacter_comic'),
        ('creator', '0002_remove_comiccreator_comic'),
        ('review', '0005_remove_review_comic'),
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comic',
        ),
    ]
