# Generated by Django 2.2.4 on 2019-10-19 16:02

import comic.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creator', '0002_remove_comiccreator_comic'),
        ('publisher', '0001_initial'),
        ('series', '0001_initial'),
        ('comic', '0002_delete_comic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_id', models.CharField(blank=True, max_length=100, null=True)),
                ('diamond_id', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('item_number', models.CharField(blank=True, max_length=50)),
                ('release_date', models.DateTimeField()),
                ('cover_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover', models.ImageField(blank=True, upload_to=comic.models.upload_location)),
                ('description', models.TextField(blank=True, default='No Description')),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=200)),
                ('printing', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('format_type', models.CharField(blank=True, max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('solicit_date', models.DateTimeField(blank=True, null=True)),
                ('is_mature', models.BooleanField(blank=True, default=False)),
                ('versions', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('variant_code', models.CharField(blank=True, max_length=100)),
                ('total_wanted', models.PositiveIntegerField(blank=True, default=0)),
                ('total_favorited', models.PositiveIntegerField(blank=True, default=0)),
                ('total_owned', models.PositiveIntegerField(blank=True, default=0)),
                ('total_read', models.PositiveIntegerField(blank=True, default=0)),
                ('creators', models.ManyToManyField(blank=True, through='creator.ComicCreator', to='creator.Creator')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Publisher')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Series')),
                ('version_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comic.Comic')),
            ],
        ),
    ]
