# Generated by Django 2.2.4 on 2019-11-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0004_comic_imprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='is_standard_issue',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
