# Generated by Django 2.2.4 on 2019-10-13 20:04

from django.db import migrations, models
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[review.models.validate_rating]),
        ),
    ]
