# Generated by Django 2.2.4 on 2019-10-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20191013_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comic',
        ),
    ]
