# Generated by Django 2.2.4 on 2019-10-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_comic'),
        ('review', '0005_remove_review_comic'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='comic.Comic'),
            preserve_default=False,
        ),
    ]
